--CRIAÇÃO DO BANCO DE DADOS
CREATE DATABASE SPMEDGROUP

--DELETAR BD
--DROP DATABASE SPMEDGROUP

--SELECIONA O BANCO DE DADOS
USE SPMEDGROUP

--CRIAÇÃO DAS TABELAS DO BANCO DE DADOS

CREATE TABLE TIPO_USUARIOS (
	ID INT IDENTITY PRIMARY KEY
	, TIPO VARCHAR(250) NOT NULL
);


CREATE TABLE ESPECIALIDADES (
	ID INT IDENTITY PRIMARY KEY
	, NOME_ESPECIALIDADE VARCHAR(250) NOT NULL
);


CREATE TABLE ENDERECOS (
	ID INT IDENTITY PRIMARY KEY
	, LOGRADOURO VARCHAR(250) NOT NULL
	, UF CHAR(2) NOT NULL
	, CEP CHAR(8) NOT NULL
);


CREATE TABLE SITUACAO (
	ID INT IDENTITY PRIMARY KEY
	, TIPO VARCHAR(250) NOT NULL
);


CREATE TABLE CLINICAS (
	ID INT IDENTITY PRIMARY KEY
	, NOME_FANTASIA VARCHAR(250) NULL
	, RAZAO_SOCIAL VARCHAR(250) NOT NULL
	, CNPJ CHAR(14) NOT NULL UNIQUE
	, HORARIO_FUNCIONAMENTO VARCHAR(100) NOT NULL
	, ID_ENDERECO INT NOT NULL FOREIGN KEY REFERENCES ENDERECOS(ID)
);


CREATE TABLE USUARIOS (
	ID INT IDENTITY PRIMARY KEY
	, EMAIL VARCHAR (250) NOT NULL UNIQUE
	, SENHA VARCHAR (100) NOT NULL
	, ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIOS(ID) DEFAULT(3) -- COMUN
);

--ADD DEFAULT
--ALTER TABLE USUARIOS ADD DEFAULT (3) FOR ID_TIPO_USUARIO

--ALTER TABLE USUARIOS ALTER COLUMN ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIOS(ID) DEFAULT(3) -- COMUN

CREATE TABLE MEDICOS (
	ID INT IDENTITY PRIMARY KEY
	, NOME_MEDICO VARCHAR(250) NOT NULL
	, CRM CHAR(5) NOT NULL UNIQUE
	, ID_CLINICA INT FOREIGN KEY REFERENCES CLINICAS(ID)
	, ID_ESPECIALIDADE INT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES(ID)
	, ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)
);


CREATE TABLE PRONTUARIOS (
	ID INT IDENTITY PRIMARY KEY
	, NOME_PACIENTE VARCHAR(250) NOT NULL
	, CPF CHAR(11) UNIQUE NOT NULL
	, RG CHAR(9) UNIQUE NOT NULL
	, DATA_NASCIMENTO DATE NOT NULL -- SE DEIXAR VARCHAR(10) ELE FUNCIONA... SEM PRECISAR CONVERTER
	, TELEFONE CHAR(13) UNIQUE -- CHAR OU INT OU VARCHAR?
	, ID_ENDERECO INT FOREIGN KEY REFERENCES ENDERECOS(ID) NOT NULL
	, ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL
);

--drop table consultas
--drop table PRONTUARIOS
--alter table prontuarios
--alter column telefone char(13)


CREATE TABLE CONSULTAS (
--IDENTITY JÁ FAZ O PROCESSO DE CLUSTERIZAÇÃO
	ID INT IDENTITY PRIMARY KEY
	, DESCRICAO TEXT NOT NULL
	, DATA_CONSULTA DATE NOT NULL
	, ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID)
	, ID_PRONTUARIO INT FOREIGN KEY REFERENCES PRONTUARIOS(ID)
	, ID_SITUACAO INT FOREIGN KEY REFERENCES SITUACAO(ID)
);

--CRIAR TABELA PACIENTES?

--DEFAULT É NONCLUSTERED
CREATE INDEX indice_cpf_prontuario
ON PRONTUARIOS(CPF)

--CRIAÇÃO COM ID, NÃO SE UTILIZA INDICES CLUSTERIZADOS VAI DAR ERRO

--ID_CONSULTAS EM VEZ DE APENAS ID?

--DROP DATABASE SPMEDGROUP